### ISSUE TITLE
每日签到的问题

### ISSUE THREAD

**Issue by Sh3nha1** [luoyefufeng/nonebot_plugin_simulator_xiuxian#1]
config.yaml里的
sign_in_xiuwei_lower_limit : 5000  # 每日签到修为下限
sign_in_xiuwei_upper_limit : 10000  # 每日签到修为上限
都这样设置了，但是签到修为还是会超过，有人直接签到修为9W

**Comment by ganchengcaiyue** [comment]
要修改这些数据需要在修仙1
(xiuxian_config.py)中修改,
config.yaml忘记删了
